[package]
name = "ed25519-dalek-rustgo"
version = "0.0.1"

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "^1.0"

[dependencies.curve25519-dalek]
version = "^0.10"
default-features = false
features = ["nightly"]

[profile.release]
debug = true
